### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by AaronmLiao** [sashafilthy/mean#2]
https://github.com/sashafilthy/mean/blob/13eb80b0b13c045c8b23a36814c92b7d471f95a0/MEAN/notthisproject/predictor.js#L22

Could replace the 0.66 with targetPct , so you could also predict with different rates, it also compares with actually input rate, right now even if you put in 0.55 it still will cal by 0.66 for else condition, but if wins/totalGames < 0.55, then your else condition console log is incorrect.

And in consoles should put as (targetPct * 100 + '%'), line 9 is making 0.66 to 0.66%. 

PS: another method is bypass the ++ part, coz looping is resource consuming:

if(0 <= targetPct < 1)    WinStrike = (targetPct * totalGames - startingWins) / (1 - targetPct);

**Comment by sashafilthy** [comment]
thanks, updated
